name: Python Application CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the code
      - name: Checkout repository
        uses: actions/checkout@v3

      # Step 2: Set up Python environment
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      # Step 3: Install dependencies
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      # Step 4: Run static analysis (linting)
      - name: Lint with flake8
        run: |
          pip install flake8
          flake8 item_search_tool.py

      # Step 5: Run tests
      - name: Run unit tests
        run: |
          python -m unittest discover tests

  build:
    runs-on: ubuntu-latest
    needs: test

    steps:
      # Step 1: Checkout the code
      - name: Checkout repository
        uses: actions/checkout@v3

      # Step 2: Set up Python environment
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      # Step 3: Install dependencies
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pyinstaller

      # Step 4: Build the application
      - name: Build application
        run: |
          pyinstaller --onefile item_search_tool.py
          ls dist/

      # Step 5: Archive the build artifact
      - name: Upload build artifact
        uses: actions/upload-artifact@v3
        with:
          name: built-application
          path: dist/
